name: Live Viper Radar Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (apt + pip)
        run: sudo apt-get update && sudo apt-get install -y gdal-bin && pip install --upgrade pip requests

      - name: Ensure output folder
        run: mkdir -p render/public

      - name: Run radar job
        run: python radar_job.py

      - name: Upload to AeonFree via FTP
        uses: sebastianpopp/ftp-action@v1.1.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: render/public
          remoteDir: ${{ secrets.FTP_PATH }}
